# Generated by Django 5.0.6 on 2025-01-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Medium')], max_length=2)),
                ('size', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
