# Generated by Django 5.0.6 on 2025-02-11 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=100),
        ),
        migrations.CreateModel(
            name='ClothesCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=100)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chai.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')])),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='chai.clothes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('clothes_varieties', models.ManyToManyField(related_name='stores', to='chai.clothes')),
            ],
        ),
    ]
