# Generated by Django 5.0.6 on 2025-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_alter_clothes_name_alter_clothes_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
