# Generated by Django 5.0.6 on 2025-03-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
