# Generated by Django 5.0.6 on 2025-03-21 09:04

import chai.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_clothes_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(default=chai.models.Category.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='chai.category'),
        ),
    ]
